[dev]
   command = "npm run dev"
[build]
  command = "npm run build"
  publish = "dist"
  functions = 'netlify/functions'
[functions."daily-db-keep-alive"]
  schedule = "@daily"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
