[dev]
   command = "bun --bun run dev"
[build]
  command = "bun x prisma generate && bun --bun run build"
  publish = ".output/public"
[functions]
    directory = ".output"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
