[dev]
   command = "bun --bun run dev"
[build]
  command = "bun upgrade && prisma generate && bun --bun run build"
  publish = "dist"
  functions = 'functions' 

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
