[dev]
   command = "bun run dev --bun "
[build]
  command = "bun upgrade && bun run build --bun"
  publish = ".nuxt/dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
