backend:
    name: github
    branch: main
    repo: wildgracevideo/wildgracevideo-website
    base_url: http://localhost:3000
    auth_endpoint: /api/admin/cms/auth

media_folder: public/uploads
public_folder: /uploads

local_backend: true

publish_mode: editorial_workflow

collections:
    - name: 'product'
      label: 'Product'
      folder: 'content/product'
      format: 'frontmatter'
      create: true
      identifier_field: 'path'
      slug: '{{slug}}'
      preview_path: 'products/{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'SEO Title', name: 'title', widget: 'string' }
          - { label: 'SEO Description', name: 'description', widget: 'text' }
          - {
                label: 'Path DO NOT CHANGE ONCE CREATED (All lowercase, separate words with -, no starting /)',
                name: 'path',
                widget: 'string',
            }
          - {
                label: 'Product Image (384 x 384 webp)',
                name: 'productImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
            }
          - {
                label: 'Published Date (This affects ordering in Shop page)',
                name: 'publishedDate',
                widget: 'datetime',
            }
          - {
                label: 'SEO Product Image Description',
                name: 'imageDescription',
                widget: 'string',
            }
          - {
                label: 'Page Preview Image (1200 x 630 webp)',
                name: 'ogImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
            }
          - {
                label: 'Top Background Image (2048 x 683 webp)',
                name: 'topBackgroundImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
            }
          - {
                label: 'Call To Action Background Image (6192 x 3456 webp)',
                name: 'callToActionBackgroundImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
            }
          - { label: 'Product Name', name: 'productName', widget: 'string' }
          - {
                label: 'Product Tagline',
                name: 'productTagline',
                widget: 'markdown',
                minimal: true,
                modes: ['rich_text'],
            }
          - {
                label: 'Short description',
                name: 'shortDescription',
                widget: 'text',
            }
          - {
                label: 'Product description',
                name: 'productDescription',
                widget: 'markdown',
                modes: ['rich_text'],
            }
          - {
                label: 'Price (Dollars)',
                name: 'priceDollars',
                widget: 'number',
                value_type: 'int',
                min: 0,
            }
          - {
                label: 'Original Price (Dollars)',
                name: 'originalPriceDollars',
                widget: 'number',
                value_type: 'int',
                min: 0,
            }
          - {
                label: 'Stripe Price ID',
                name: 'stripePriceId',
                widget: 'string',
            }
          - {
                label: 'Send Grid Template ID',
                name: 'sendGridTemplateId',
                widget: 'string',
            }
          - {
                label: 'Omnisend Purchase Tag',
                name: 'omnisendTag',
                widget: 'string',
            }
          - label: "What's Inside Components"
            name: 'whatsInsideComponents'
            widget: 'list'
            fields:
                - {
                      label: 'Text',
                      name: 'text',
                      widget: 'markdown',
                      modes: ['rich_text'],
                      minimal: true,
                  }
          - {
                label: 'Call To Action title',
                name: 'callToActionTitle',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: true,
            }
          - {
                label: 'Call To Action subheading',
                name: 'callToActionSubheading',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: true,
            }

    - name: 'portfolio'
      label: 'Portfolio'
      folder: 'content/portfolio'
      format: 'frontmatter'
      create: false
      identifier_field: 'title'
      slug: 'portfolio'
      preview_path: 'portfolio'
      editor:
          preview: false
      fields:
          - { label: 'SEO Title', name: 'title', widget: 'string' }
          - { label: 'SEO Description', name: 'description', widget: 'text' }
          - { label: 'Page Title', name: 'heading', widget: 'string' }
          - {
                label: 'Main Reel Youtube ID',
                name: 'mainReelYoutubeId',
                widget: 'string',
            }
          - {
                label: 'Main Reel SEO Name',
                name: 'mainReelName',
                widget: 'string',
            }
          - {
                label: 'Main Reel SEO Description',
                name: 'mainReelAlt',
                widget: 'string',
            }
          - label: 'Youtube Videos'
            name: 'youtubeVideos'
            widget: 'list'
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'markdown',
                      modes: ['rich_text'],
                      minimal: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'markdown',
                      modes: ['rich_text'],
                      minimal: true,
                  }
                - { label: 'Youtube ID', name: 'youtubeId', widget: 'string' }
                - { label: 'SEO Description', name: 'alt', widget: 'text' }

    - name: 'service'
      label: 'Service'
      folder: 'content/service'
      format: 'frontmatter'
      create: true
      identifier_field: 'path'
      slug: '{{slug}}'
      preview_path: 'services/{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'SEO Title', name: 'title', widget: 'string' }
          - { label: 'SEO Description', name: 'description', widget: 'text' }
          - {
                label: 'Page Preview Image (1200 x 630 webp)',
                name: 'ogImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                required: false,
            }
          - {
                label: 'Path DO NOT CHANGE ONCE CREATED (All lowercase, separate words with -, no starting /)',
                name: 'path',
                widget: 'string',
            }
          - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
          - { label: 'Product Title', name: 'productTitle', widget: 'string' }
          - { label: 'Menu Title', name: 'menuTitle', widget: 'string' }
          - {
                label: 'Menu Description',
                name: 'menuDescription',
                widget: 'string',
            }
          - {
                label: 'Menu Hero Icon Name (https://heroicons.com/outline Only pick from outline i.e: academic-cap)',
                name: 'menuIcon',
                widget: 'string',
            }
          - {
                label: 'Product Description',
                name: 'productDescription',
                widget: 'markdown',
                modes: ['rich_text'],
            }
          - {
                label: 'Product Subtext',
                name: 'productSubtext',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: true,
            }
          - label: 'Packages'
            name: 'packages'
            widget: 'list'
            fields:
                - {
                      label: 'Title (Without "The")',
                      name: 'title',
                      widget: 'string',
                  }
                - {
                      label: 'Price',
                      name: 'price',
                      widget: 'number',
                      required: false,
                  }
                - label: 'Components'
                  name: 'components'
                  widget: 'list'
                  fields:
                      - {
                            label: 'Title',
                            name: 'title',
                            widget: 'string',
                            required: false,
                        }
                      - {
                            label: 'Description (Non-bold component description, use if title is blank)',
                            name: 'description',
                            widget: 'markdown',
                            modes: ['rich_text'],
                            minimal: true,
                            required: false,
                        }
                      - {
                            label: 'Contents',
                            name: 'contents',
                            widget: 'markdown',
                            modes: ['rich_text'],
                            minimal: true,
                        }
          - label: 'Add-Ons'
            name: 'addOns'
            widget: 'list'
            required: false
            summary: '{{fields.id}}'
            fields:
                - label: 'Numeric identifier (1 matches the color of the first component in a package)'
                  name: 'id'
                  widget: 'number'
                - label: 'Components'
                  name: 'components'
                  widget: 'list'
                  fields:
                      - {
                            label: 'Contents',
                            name: 'contents',
                            widget: 'markdown',
                            modes: ['rich_text'],
                            minimal: true,
                        }
          - {
                label: 'Disclaimer',
                name: 'disclaimer',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: true,
            }

    - name: 'home'
      label: 'Home'
      folder: 'content/home'
      format: 'frontmatter'
      create: false
      identifier_field: 'title'
      preview_path: '/'
      slug: 'home'
      editor:
          preview: false
      fields:
          - { label: 'SEO Title', name: 'title', widget: 'string' }
          - { label: 'SEO Description', name: 'description', widget: 'text' }
          - { label: 'Reel Video SEO Description', name: 'videoTitle', widget: 'text' }
          - {
                label: 'Reel Video Thumbnail Image',
                name: 'thumbnailImage',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
            }
          - {
                label: 'Page Title',
                name: 'pageTitle',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: true,
            }
          - {
                label: 'Page tagline',
                name: 'pageTagline',
                widget: 'markdown',
                modes: ['rich_text'],
                minimal: false,
            }
          
